---
title: Bare
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: posts
    type: posts
  values:
    layout: default
    permalink: "/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
  values:
    layout: default
url: http://www.sampledomainpleasechange.com
baseurl: 
permalink: pretty
exclude:
- ".git"
- ".gitignore"
- ".DS_Store"
- ".sass-cache"
- package.json
- Gruntfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- LICENSE
